#ifndef __PHAPI_H__
#define __PHAPI_H__

#define DEVICE_SHOST_NAME L"ph"
#define DEVICE_NAME (L"\\Device\\" DEVICE_SHOST_NAME)
#define SYMBOLIC_LINK_SHORT_NAME L"link_ph"
#define SYMBOLIC_LINK_NAME (L"\\DosDevices\\" SYMBOLIC_LINK_SHORT_NAME)

#define KPH_CTL_CODE(x) CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800 + x, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define IO_READ_VIRTUAL_MEMORY KPH_CTL_CODE(1)
#define IO_WRITE_VIRTUAL_MEMORY KPH_CTL_CODE(2)
#define IO_GET_PROCESS_ID KPH_CTL_CODE(3)
#define IO_GET_PROCESS_BASE_ADDRESS KPH_CTL_CODE(4)

typedef struct _READ_VIRTUAL_MEMORY
{
	ULONG ProcessId;

	ULONG Address;
	ULONG Response;
	ULONG Size;

}READ_VIRTUAL_MEMORY, *PREAD_VIRTUAL_MEMORY;

typedef struct _WRITE_VIRTUAL_MEMORY
{
	ULONG ProcessId;

	ULONG Address;
	ULONG Value;
	ULONG Size;

}WRITE_VIRTUAL_MEMORY, *PWRITE_VIRTUAL_MEMORY;

#endif // !__PHAPI_H__

